language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - LOCAL_SETTINGS_FILE="local.base.cfg#test" ./manage.py test
