dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

addons:
    postgresql: "10"
    apt:
      packages:
        - postgresql-10-postgis-2.4

services:
    - postgresql

install:
  - pip install -r requirements.txt

before_script:
    - psql -U postgres -c 'create user aol;'
    - psql -U postgres -c 'create database aol owner aol;'
    - psql -U postgres -d aol -c 'create extension postgis;'
    - psql -U postgres -d aol -c 'create extension hstore;'
    - psql -U postgres -c 'create database test_aol owner aol;'
    - psql -U postgres -d test_aol -c 'create extension postgis;'
    - psql -U postgres -d test_aol -c 'create extension hstore;'

script:
    - LOCAL_SETTINGS_FILE="local.base.cfg#travis" python manage.py test --keepdb
