version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        # this value is a soft-reservation of the subnet in
        # order to reduce friction w.r.t. a given local docker
        # environment and project configuration.
        # 
        # if you encounter network definition conflicts, change
        # the value below and revise its use in 'local.*.cfg'.
        - subnet: 172.20.0.0/16

services:
  postgres:
    image: kartoza/postgis:9.6-2.4
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aol
      - POSTGRES_PASS=aol
      - POSTGRES_DBNAME=aol
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

  aol:
    image: psu.oit.wdt/aol
    build: app
    user: aol
    environment:
      - LOCAL_SETTINGS_FILE=local.docker.cfg
      - WSGI_ROOT=/webapps/aol
      - WSGI_VENV=/webapps/aol/venv-docker
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - ./:/webapps/aol
    depends_on:
      - postgres
